[#ftl]
[@b.navmenu]
	[@ems.guard res="/teach/grade/lesson/input-switch"][@b.navitem title="成绩录入开关设置" href="/teach/grade/lesson/input-switch" /][/@]
	[@ems.guard res="/teach/grade/setting/rate"][@b.navitem title="成绩记录方式设置" href="/teach/grade/setting/rate" /][/@]
	[@ems.guard res="/teach/grade/setting/config"][@b.navitem title="成绩全局设置" href="/teach/grade/setting/config" /][/@]
[/@]