[#ftl/]
[#include "/template/macros.ftl"/]
[@b.head/]
[@b.toolbar title="班级排名"]
	bar.addBack("${b.text('action.back')}");
[/@]
[@b.div style="margin-top:10px;text-align:center;"]
	[#if rankings?first.std.project.minor]
		班级代码:${rankings?first.std.adminclass.code} 
		班级名称:[@i18nName rankings?first.std.adminclass/]
		所在院系:[@i18nName (rankings?first.std.adminclass.secondMajor.department)?if_exists/] 
		所属专业:[@i18nName (rankings?first.std.adminclass.secondMajor)?if_exists/] 
		方向:[@i18nName (rankings?first.std.adminclass.secondAspect)?if_exists/]
	[#else]
		班级代码:${rankings?first.std.adminclass.code} 
		班级名称:[@i18nName rankings?first.std.adminclass/] 
		所在院系:[@i18nName rankings?first.std.adminclass.department?if_exists/] 
		所属专业:[@i18nName rankings?first.std.adminclass.major?if_exists/] 
		方向:[#if rankings?first.std.adminclass.direction?exists][@i18nName rankings?first.std.adminclass.direction/][#else]无[/#if]
	[/#if]
	[@b.grid items=rankings var="stdGpa"]
		[@b.row]
			[@b.col title="学号"]${stdGpa.std.code}[/@]
			[@b.col title="姓名"]${stdGpa.std.name}[/@]
			[@b.col title="总平均分"]${stdGpa.gpa!}[/@]
			[@b.col title="排名"]${stdGpa_index+1}[/@]
		[/@]
	[/@]
[/@]
[@b.foot/]