[#ftl/]
[#include "/template/macros.ftl"/]
[@b.head/]
[@b.toolbar title="专业排名"]
	bar.addBack("${b.text('action.back')}");
[/@]
	[@b.div style="margin-top:10px;text-align:center;"]
		[#if rankings?first.std.project.minor]
				专业代码:${rankings?first.std.major.code} 
				专业名称:[@i18nName rankings?first.std.major/]
				所在院系:[@i18nName (rankings?first.std.major.secondMajor.department)?if_exists/]
				学历层次:[#list rankings?first.std.major.educations?if_exists as education][@i18nName education/][#if education_has_next],[/#if][/#list]
		[#else]
				专业代码:${rankings?first.std.major.code} 
				专业名称:[@i18nName rankings?first.std.major/]
				所在院系:[@i18nName rankings?first.std.major.department?if_exists/]
				学历层次:[#list rankings?first.std.major.educations?if_exists as education][@i18nName education/][#if education_has_next],[/#if][/#list]
		[/#if]
	[/@]
	[#include "../gradeMacros.ftl"/]
	[@b.grid items=rankings var="stdGpa"]
		[@b.row]
			[@b.col title="学号"]${stdGpa.std.code}[/@]
			[@b.col title="姓名"]${stdGpa.std.name}[/@]
			[@b.col title="总平均绩点"]${stdGpa.gpa!}[/@]
			[@b.col title="排名"]${stdGpa_index+1}[/@]
		[/@]
	[/@]
[@b.foot/]