[#ftl]
[@b.head/]
[@b.toolbar title="修改学位"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!update?id=${courseType.id}" theme="list"]
    [@b.textfield name="courseType.code" label="代码" value="${courseType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseType.name" label="名称" value="${courseType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseType.enName" label="英文名" value="${courseType.enName!}" maxlength="100"/]
    [@b.startend label="生效失效时间" 
      name="courseType.beginOn,courseType.endOn" required="false,false" 
      start=courseType.beginOn end=courseType.endOn format="date"/]
    [@b.textfield name="courseType.remark" label="备注" value="${courseType.remark!}" maxlength="3"/]
    [@b.radios label="是否理论课"  name="courseType.theoretical" value=courseType.theoretical items="1:common.yes,0:common.no"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]