[#ftl]
[@b.head/]
	[@b.textfields names="gradeModifyApply.course.code;attr.courseNo,gradeModifyApply.course.name;attr.courseName,gradeModifyApply.std.code;attr.stdNo,gradeModifyApply.std.name;attr.personName,gradeModifyApply.applyer;申请人" maxlength="25"/]
	[#include "/template/major3Select.ftl"/]
	[@majorSelect id="s1" projectId="gradeModifyApply.std.project.id" educationId="gradeModifyApply.std.education.id" departId="gradeModifyApply.std.majorDepart.id" majorId="gradeModifyApply.std.major.id" directionId="gradeModifyApply.std.direction.id" stdTypeId="gradeModifyApply.std.type.id"/]
	[@b.select  label="grade.scoreType" name="gradeModifyApply.gradeType.id" items=gradeTypes?sort_by("code") empty="..."/]
	[@b.select label="attr.graduate.auditStatus" items={} name="applyStatus"]
		[#list statuses as status]
			[#if status.name() == 'NOT_AUDIT' || status.name() == 'DEPART_AUDIT_PASSED' || status.name() == 'DEPART_AUDIT_UNPASSED' || status.name() == 'GRADE_DELETED']
				<option value="${status.name()}">${status.fullName}</option>
			[/#if]
		[/#list]
	[/@]
[@b.foot/]