[#ftl]
[@b.head/]
	
[@b.grid items=gradeLogs var="gradeLog" filterable="false"]
	[@b.row]
    	[@b.col  property="id" title="编号" ]
    		[@b.a href="!info?id=${gradeLog.id}" title="点击查看详情"]${gradeLog.id!}[/@]
    	[/@]
    	[@b.col  property="student.code" title="学号" /]
		[@b.col  property="student.name" title="姓名" /]
		[@b.col  property="lessonNo" title="课程序号" /]
		[@b.col  property="courseName" title="课程名称" /]
		[@b.col  property="operator" title="操作人" /]
		[@b.col  property="operateAt" title="操作时间" ]${gradeLog.operateAt?string("yyyy-MM-dd HH:mm:ss")}[/@]
		[@b.col  property="ip" title="IP" /]
		[@b.col  property="entry" title="访问路径(URI)" /]
		[@b.col  property="type" title="操作类型" /]
[/@]
[/@]
