[#ftl]
[@b.head/]
[#include "/template/macros.ftl"/]
[@b.grid items=gradeModifyApplys var="gradeModifyApply"]
	[@b.row]
		[@b.col property="course.code" title="attr.courseNo" width="5%"/]
		[@b.col property="course.name" title="attr.courseName" width="8%"/]
		[@b.col property="std.code" title="attr.stdNo" width="5%"/]
		[@b.col property="std.name" title="attr.personName" width="6%"/]
		[@b.col property="gradeType.name" title="grade.scoreType" width="6%"/]
		[@b.col property="origScoreText" title="field.exam.exam" width="6%"/]
		[@b.col property="scoreText" title="修改后成绩" width="6%"/]
		[@b.col property="examStatusBefore.name" title="exam.situation" width="6%"/]
		[@b.col property="examStatus.name" title="修改后考试情况" width="7%"/]
		[@b.col property="status" title="attr.graduate.auditStatus" width="7%"]${gradeModifyApply.status.fullName}[/@]
		[@b.col property="createdAt" title="attr.graduate.degreeApplication.degreeApplyTime" width="14%"]${gradeModifyApply.createdAt?string('yyyy-MM-dd HH:mm')}[/@]
		[@b.col property="applyer" title="申请人" width="6%"/]
		[@b.col property="applyReason" title="申请理由" width="6%"/]
		[@b.col property="auditer" title="院系审核人" width="6%"/]
		[@b.col property="finalAuditer" title="最终审核人" width="6%"/]
	[/@]
[/@]
[@b.foot/]
