[#ftl]
[@b.head/]
<!--修改ITEMS内容  把原来的lessonTeacher修改为teachQualities--->
[@b.form name="taskListForm" id="taskListForm" target="contentDiv" ]
	[@b.grid items=teachQualities! var="lesson"]
		[@b.row]
			[@b.col width="10%" property="no" title="序号" /]
			[@b.col width="14%" property="course.code" title="attr.courseNo" maxlength="3"/]
			[@b.col width="22%" property="course.name" title="attr.courseName" /]
			[@b.col width="20%" property="courseType.name" title="entity.courseType" /]
			[@b.col width="22%" property="teachClass.name" title="entity.teachClass"]${lesson.teachClass.name?html!}[/@]
			[@b.col width="22%" property="teacher.name" title="教师"]
				[#list (lesson.teachers)! as teacher]
					${teacher.name?html!}&nbsp;&nbsp;
				[/#list]
			[/@]
		[/@]
	[/@]
[/@]
[@b.foot /]
