[#ftl]
[@b.grid items=lessons var="lesson"]
	[@b.row]
		[@b.col width="5%" title="attr.index"]${lesson_index+1}[/@]
		[@b.col width="10%" title="attr.taskNo"]${(lesson.no)?if_exists}[/@]
		[@b.col width="19%" title="attr.courseName"]${(lesson.course.name)?if_exists}[/@]
		[@b.col width="12%" title="entity.courseType"]${(lesson.courseType.name)?if_exists}[/@]
		[@b.col width="5%" title="attr.credit"]${(lesson.course.credits)?if_exists}[/@]
		[@b.col width="5%" title="attr.weeks"]${(lesson.courseSchedule.weeks)?if_exists}[/@]
		[@b.col width="5%" title="course.weekHour"]${(lesson.courseSchedule.period)?if_exists}[/@]
		[@b.col width="5%" title="task.studentNum"]${lesson.teachClass.courseTakes?size}[/@]
		[@b.col width="17%" title="期末总评成绩"]
			[@b.a href="/teach/grade/lesson/report!blank?lesson.id=${lesson.id}" target="_blank"]<U>空白登分册</U>[/@]
			[@b.a href="!info?lessonId=${lesson.id}" target="_blank"]<U>查看</U>[/@]
			[#if (gradeStates.get(lesson.id).getState(GA).confirmed)!false]
				[@b.a href="!report?lessonIds=${lesson.id}" target="_blank"]<U>打印</U>[/@]
				[#if gradeStates.get(lesson.id).getState(GA).published]已发布[#else]已提交[/#if]
			[#else]
				[#assign openEnd=false]
				[#list gradeInputSwitch.types as t][#if t.id==2][#assign openEnd=true][#break/][/#if][/#list]
				[#if gradeInputSwitch.checkOpen() && openEnd]
				[@b.a href="!inputTask?lessonId=${lesson.id}" target="_blank"]<U>录入</U>[/@]
				[/#if]
			[/#if]
		[/@]
		[@b.col width="17%" title="grade.makeupdelay"]
		  [#if (makeupTakeCounts.get(lesson)!0)>0]
			[@b.a href="/teach/grade/lesson/report!blank?lesson.id=${lesson.id}&makeup=1" target="_blank"]<U>空白登分册</U>[/@]
			[@b.a href="admin-makeup!info?lessonId=${lesson.id}" target="_blank"]<U>查看</U>[/@]
			[#if (gradeStates.get(lesson.id).getState(MAKEUP).confirmed)!false ||  (gradeStates.get(lesson.id).getState(DELAY).confirmed)!false]
				[@b.a href="!report?lessonIds=${lesson.id}&gradeType.id=${MAKEUP.id}&gradeType.id=${DELAY.id}" target="_blank"]<U>打印</U>[/@]
				[#if ((gradeStates.get(lesson.id).getState(MAKEUP).published)!false)||((gradeStates.get(lesson.id).getState(DELAY).published)!false) ]已发布[#else]已提交[/#if]
			[#else]
				[#assign openMakeup=false]
				[#list gradeInputSwitch.types as t][#if t.id==4 || t.id==6][#assign openMakeup=true][#break/][/#if][/#list]
				[#if gradeInputSwitch.checkOpen() && openMakeup]
				[@b.a href="!inputTask?lessonId=${lesson.id}" target="_blank"]<U>录入</U>[/@]
				[/#if]
			[/#if]
		  [/#if]
		[/@]
	[/@]
[/@]
[#if gradeInputSwitch.startAt??]
<p>录入时间:${gradeInputSwitch.startAt?string("yyyy-MM-dd HH:mm")}~${gradeInputSwitch.endAt?string("yyyy-MM-dd HH:mm")}<br/>${(gradeInputSwitch.remark!)?html}</p>
[/#if]