[#ftl/]
[@b.head/]
[#include "/template/macros.ftl"/]
	[@b.form name="multiStdGradeListForm" action="!adminClassList" target="contentDiv"]
	 [@b.grid items=adminclasses var="adminclass" filterable="true"]
	 	[@b.gridbar]
	 	bar.addItem("查看","displayMultiStdSetting()");
	 	[/@]
	 	[@b.row]
	 		[@b.boxcol/]
	 		[@b.col property="grade" title="std.grade" width="10%"/]
	 		[@b.col property="name" title="attr.name" width="10%"]
 				[@b.a href="!classGradeReport?adminclass.ids=${adminclass.id}&semester.id=${(Parameters['semester.id'])!}" target="_blank" title="查看行政班级学生成绩信息"][@i18nName adminclass/][/@]
	 		[/@]
	 		[@b.col property="stdType.name" title="entity.studentType" width="10%"/]
	 		[@b.col property="department.name" title="院系" width="20%"/]
	 		[@b.col property="major.name" title="entity.major" width="30%"/]
	 		[@b.col property="direction.name" sort="adminclass.direction" title="entity.direction" width="20%"/]
	 	[/@]
	 [/@]
  [/@]
	[#include "../termReport/multiStdReportSetting.ftl"/]
[@b.foot/]
