[#ftl]
[@b.head/]
[#include "/template/macros.ftl"/]
[#if lessons??]
	[@b.grid items=lessons var="lesson"]
		[@b.gridbar]
			bar.addItem("${b.text('action.export')}",action.exportData("no:attr.taskNo,course.code:attr.courseNo,course.name:attr.courseName,teachClass.name:entity.teachClass,teachers:common.teacher,teachClass.stdCount:attr.stdNum,course.credits:attr.credit,course.period:workload.courseTime",null,"&fileName=课程成绩统计&status=${status!}&gradeTypeId=${gradeTypeId!}&departmentId=${departmentId!}"));
			bar.addBack("${b.text('action.back')}");
		[/@]
		[@b.row]
			[@b.col property="no" title="attr.taskNo" width="10%"/]
			[@b.col property="course.code" title="attr.courseNo" width="10%"/]
			[@b.col property="course.name" title="attr.courseName" width="22%"/]
			[@b.col property="teachClass.name" title="entity.teachClass" width="35%"/]
			[@b.col width="10%" property="teachers[0].name" title="entity.teacher" sortable="false"][@getTeacherNames lesson.teachers/][/@]
			[@b.col  title="attr.stdNum" width="5%" property="teachClass.stdCount"/]
			[@b.col property="course.credits" title="attr.credit" width="5%"/]
			[@b.col property="course.period" title="课时" width="5%"/]
		[/@]
	[/@]
[#else]
	[@b.grid items=courseGradeStates var="gradeState"]
		[@b.gridbar]
			bar.addItem("${b.text('action.export')}",action.exportData("lesson.no:attr.taskNo,lesson.course.code:attr.courseNo,lesson.course.name:attr.courseName,lesson.teachClass.name:entity.teachClass,teachers:common.teacher,lesson.teachClass.stdCount:attr.stdNum,lesson.course.credits:attr.credit,lesson.course.period:workload.courseTime",null,"&fileName=课程成绩统计&status=${status!}&gradeTypeId=${gradeTypeId!}&departmentId=${departmentId!}"));
			bar.addBack("${b.text('action.back')}");
		[/@]
		[@b.row]
			[@b.col property="lesson.no" title="attr.taskNo" width="10%"/]
			[@b.col property="lesson.course.code" title="attr.courseNo" width="10%"/]
			[@b.col property="lesson.course.name" title="attr.courseName" width="22%"/]
			[@b.col property="lesson.teachClass.name" title="entity.teachClass" width="35%"/]
			[@b.col width="10%" property="teachers[0].name" title="entity.teacher" sortable="false"][@getTeacherNames gradeState.lesson.teachers/][/@]
			[@b.col  title="attr.stdNum" width="5%" property="lesson.teachClass.stdCount"/]
			[@b.col property="lesson.course.credits" title="attr.credit" width="5%"/]
			[@b.col property="lesson.course.period" title="课时" width="5%"/]
		[/@]
[/@]
[/#if]
[@b.foot/]