[#ftl]
[@b.head/]
[#include "/template/macros.ftl"]
[@b.grid items=results var="stat"]
	[@b.row]
		[@b.col title="院系"][@i18nName stat.department/]<input type="hidden" name="courseGrade.lesson.teachDepart" value="${stat.department.id}"/>[/@]
		[@b.col title="成绩类型"][@i18nName stat.gradeType/][/@]
		[@b.col title="未录入"]
			[@b.a href="!search?department.id="+stat.department.id+"&gradeType.id="+stat.gradeType.id target="contentDiv"]
			${ (unInputLessonMap.get(stat.department.id+"_"+stat.gradeType.id))!}
			[/@]
		[/@]
		[@b.col title="未提交"][@b.a href="!search?department.id="+stat.department.id+"&gradeType.id="+stat.gradeType.id+"&status=0" target="contentDiv"]${(stat.unpublished)!}[/@][/@]
		[@b.col title="已提交未发布"][@b.a href="!search?department.id="+stat.department.id+"&gradeType.id="+stat.gradeType.id+"&status=1" target="contentDiv"]${(stat.submited)!}[/@][/@]
		[@b.col title="已发布"][@b.a href="!search?department.id="+stat.department.id+"&gradeType.id="+stat.gradeType.id+"&status=2" target="contentDiv"]${(stat.published)!}[/@][/@]
	[/@]
[/@]
[@b.foot/]