[#ftl]
[@b.grid items=lessons var="lesson"]
	[@b.row]
		[@b.col width="5%" title="attr.index"]${lesson_index+1}[/@]
		[@b.col width="10%" title="attr.taskNo"]${(lesson.no)?if_exists}[/@]
		[@b.col width="19%" title="attr.courseName"]${(lesson.course.name)?if_exists}[/@]
		[@b.col width="12%" title="entity.courseType"]${(lesson.courseType.name)?if_exists}[/@]
		[@b.col width="5%" title="attr.credit"]${(lesson.course.credits)?if_exists}[/@]
		[@b.col width="5%" title="attr.weeks"]${(lesson.courseSchedule.weeks)?if_exists}[/@]
		[@b.col width="5%" title="course.weekHour"]${(lesson.courseSchedule.period)?if_exists}[/@]
		[@b.col width="5%" title="task.studentNum"]${lesson.teachClass.courseTakes?size}[/@]
		[@b.col width="17%" title="期末总评成绩"]
			[@b.a href="!info?lesson.id=${lesson.id}" target="_blank"]<U>查看</U>[/@]
			[@b.a href="!report?lessonIds=${lesson.id}" target="_blank"]<U>打印</U>[/@]
			[#if inputableLessonIds?seq_contains(lesson.id)]
				<a href="${b.url("!inputReady?lesson.id=${lesson.id}")}" target="_grade_input_window"><U>录入</U></a>
			[/#if]
		[/@]
	[/@]
[/@]