[#ftl]
[@b.head/]
[@b.toolbar title="新建学生分类标签"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="stdLabel.code" label="代码" value="${stdLabel.code!}" required="true" maxlength="20"/]
    [@b.textfield name="stdLabel.name" label="名称" value="${stdLabel.name!}" required="true" maxlength="20"/]
    [@b.select name="stdLabel.labelType.id" label="标签类型" value="${(stdLabel.labelType.id)!}" required="true" 
               style="width:200px;" items=labelTypes option="id,name" empty="..."/]
    [@b.textfield name="stdLabel.enName" label="英文名" value="${stdLabel.enName!}" maxlength="100"/]
    [@b.startend label="生效失效时间" 
      name="stdLabel.beginOn,stdLabel.endOn" required="false,false" 
      start=stdLabel.beginOn end=stdLabel.endOn format="date"/]
    [@b.textfield name="stdLabel.remark" label="备注" value="${stdLabel.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]