[#ftl]
[@b.head/]
[@b.toolbar title="新建学位"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="courseCategory.code" label="代码" value="${courseCategory.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseCategory.name" label="名称" value="${courseCategory.name!}" required="true" maxlength="20"/]
    [@b.textfield name="courseCategory.enName" label="英文名" value="${courseCategory.enName!}" maxlength="100"/]
    [@b.startend label="生效失效日期" 
      name="courseCategory.beginOn,courseCategory.endOn" required="false,false" 
      start=courseCategory.beginOn end=courseCategory.endOn format="date"/]
    [@b.textfield name="courseCategory.remark" label="备注" value="${courseCategory.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]