[#ftl]
[@b.grid items=courseGrades var="grade"]
	[@b.row]
		[@b.boxcol/]
		[@b.col property="std.code" title="attr.stdNo"]
			[@b.a href="studentSearch!info?studentId=${grade.std.id}" target="_blank" title="查看学生基本信息"]${(grade.std.code)?if_exists}[/@]
		[/@]
		[@b.col property="std.name" title="attr.personName"]
			[@b.a href="stdGradeSearch.action!info?courseGradeId=${(grade.id)?default('false')}" target="contentDiv" title="查看成绩详情"]${(grade.std.name)?if_exists}[/@]
		[/@]
		[@b.col property="lessonNo" title="attr.taskNo"/]
		[@b.col property="course.code" title="attr.courseNo"/]
		[@b.col property="course.name" title="entity.course"/]
		[@b.col property="courseType.name" title="entity.courseType"/]
		[@b.col property="score" title="成绩"][#if grade.passed]${(grade.getScore())?if_exists}[#else]<font color="red">${(grade.getScore())?if_exists}</font>[/#if][/@]
		[@b.col property="course.credits" title="attr.credit"/]
		[@b.col property="gp" title="绩点"][#if grade.passed]${(grade.gp?string("#.##"))?if_exists}[#else]<font color="red">${(grade.gp?string("#.##"))?if_exists}</font>[/#if][/@]
		[@b.col property="semester" title="学年学期"]${(grade.semester.schoolYear)?if_exists}学年 ${(grade.semester.name)?if_exists?replace('0','第')}学期[/@]
	[/@]
[/@]
