[#ftl/]
[#include "/template/macros.ftl"/]
[@b.head/]
	[@b.toolbar title="成绩发布统计结果"/]
	[@b.grid items=results var="result"]
		[@b.row]
			[@b.col title="成绩类型"][@i18nName result[0]?if_exists/][/@]
			[@b.col title="尚未发布"]${result[2]}[/@]
			[@b.col title="已经发布"]${result[1]}[/@]
		[/@]
	[/@]
[@b.foot/]
