[#ftl/]
[#include "/template/macros.ftl"/]
[@b.head/]
[@b.toolbar title="成绩状态统计结果"]
	bar.addPrint();
[/@]
	[@b.grid items=results var="result"]
		[@b.row]
			[@b.col title="成绩类型"][@i18nName result[0]?if_exists/][/@]
			[@b.col title="未录入"]${(result[4])!}[/@]
			[@b.col title="已录入"]${(result[1])!}[/@]
			[@b.col title="已确认"]${(result[2])!}[/@]
			[@b.col title="已发布"]${(result[3])!}[/@]
		[/@]
	[/@]
[@b.foot/]