[#ftl]
[@b.head/]
[@b.grid items=adminclasss var="adminclass"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="code" title="代码"]${adminclass.code}[/@]
    [@b.col width="20%" property="name" title="名称"][@b.a href="!info?id=${adminclass.id}"]${adminclass.name}[/@][/@]
    [@b.col width="15%" property="abbreviation" title="简称"]${adminclass.abbreviation!}[/@]
      [@b.col width="20%" property="instructors" title="辅导员"]
    [#list adminclass.instructors as instructor]
        ${instructor.name!}
        [#if instructor_has_next]<br>[/#if]
      [/#list]
      [/@]
    [@b.col width="20%" property="tutors" title="班导师"]
      [#list adminclass.tutors as tutor]
        ${tutors.name!}
        [#if tutors_has_next]<br>[/#if]
      [/#list]
      [/@]
    [@b.col width="15%" property="department" title="院系"]${adminclass.department.name!}[/@]
    [@b.col width="15%" property="major" title="专业"]${adminclass.major.name!}[/@]
    [@b.col width="15%" property="direction" title="方向"]${adminclass.direction.name!}[/@]
    [@b.col width="15%" property="stdType" title="学生类别"]${adminclass.stdType.name!}[/@]
    [@b.col width="15%" property="grade" title="年级"]${adminclass.grade!}[/@]
    [@b.col width="15%" property="stdCount" title="学籍有效人数"]${adminclass.stdCount!}[/@]
    [@b.col width="20%" property="beginOn" title="生效时间"]${adminclass.beginOn!}[/@]
    [@b.col width="20%" property="endOn" title="失效时间"]${adminclass.endOn!}[/@]
  [/@]
[/@]
[@b.foot/]
