[#ftl]
[@b.grid items=grades var="grade" title="${course.name}(${course.code}) ${course.credits}学分.不及格人数${count}"]
	[@b.row]
		[@b.col property="std.code" title="attr.stdNo" width="10%"/]
		[@b.col property="std.name" title="attr.personName" width="8%"/]
		[@b.col property="std.department.name" title="院系" width="17%"/]
		[@b.col property="std.major.name" title="专业" width="20%"/]
		[@b.col property="std.adminclass.name" title="班级" width="10%"/]
		[@b.col property="courseType.name" title="entity.courseType" width="15%"/]
		[@b.col property="score" title="成绩" width="5%"][#if grade.passed]${(grade.getScore())?if_exists}[#else]<font color="red">${(grade.getScore())?if_exists}</font>[/#if][/@]
		[@b.col property="gp" title="绩点" width="5%"][#if grade.passed]${(grade.gp?string("#.##"))?if_exists}[#else]<font color="red">${(grade.gp?string("#.##"))?if_exists}</font>[/#if][/@]
		[@b.col property="semester" title="学年学期" width="10%"]${grade.semester.schoolYear} ${grade.semester.name}[/@]
	[/@]
[/@]
