[#ftl]
[@b.head/]
[@b.toolbar title="管理行政班列表"/]
	[@b.grid items=adminclasses var="adminclass"]
		[@b.gridbar]
			bar.addItem("获取学生名单",action.single("search"));
		[/@]
		[@b.row]
			[@b.boxcol/]
			[@b.col property="code" title="attr.code"/]
			[@b.col property="name" title="attr.name"/]
			[@b.col property="grade" title="adminClass.grade"/]
			[@b.col title="学生人数"]${(adminclass.students)?size}[/@]
			[@b.col property="department.name" title="common.college"/]
			[@b.col property="major.name" title="entity.major"/]
		[/@]
	[/@]
[@b.foot/]
