[#ftl]
[@b.head/]
[@b.toolbar title='不及格成绩列表']
	bar.addClose();
[/@]
[#assign gradeStatus={'0':'新添加','1':'已提交','2':'已发布'}]
[#assign gradeStatusColor={'0':'#FFBB66','1':'#99FF99','2':'white'}]
[#assign gradeTypes=gradeTypes?sort_by("code")/]

<table width="100%" style="border-collapse: collapse;border:solid;border-width:0px;"><tr><td>序号:${lesson.no!} 课程:${lesson.course.name!}</td>[#list gradeStatus?keys as ss]<td style="background-color:${gradeStatusColor[ss]};text-align:center" width="80px">${gradeStatus[ss]}</td>[/#list]</tr></table>
[#if gradeTypes?size>0][#assign gradeWidth=50/gradeTypes?size][/#if]
[@b.grid items=grades var="courseGrade"]
	[@b.row]
		[@b.boxcol/]
		[@b.col width="4%" title="序号"]${courseGrade_index+1}[/@]
		[@b.col width="10%" property="std.code" title="attr.stdNo"/]
		[@b.col width="10%" property="std.name" title="attr.personName"/]
		[@b.col width="8%" property="courseTakeType.name" title="修读类别"/]
		[#list gradeTypes as gradeType]
		[#assign examGrade=courseGrade.getExamGrade(gradeType)!"null"/]
		[#if examGrade!="null"]
		[@b.col title=gradeType.name property="gradeType.${gradeType.id}" width="${gradeWidth}%" style="background-color:${gradeStatusColor[examGrade.status?string]}"]
			[#if !examGrade.passed]<font color='red'>${examGrade.scoreText!"--"}[#if examGrade.examStatus.id!=NORMAL.id]<sup>${examGrade.examStatus.name}</sup>[/#if]</font>
			[#else]
			${examGrade.scoreText!"--"}[#if examGrade.examStatus.id!=NORMAL.id]<sup>${examGrade.examStatus.name}</sup>[/#if]
			[/#if]
		[/@]
		[#else][@b.col title=gradeType.name width="9%" property="gradeType.${gradeType.id}"][/@][/#if]
		[/#list]
		[#if courseGrade??]
		[@b.col width="9%" property="scoreText" title=FINAL.name style="background-color:${gradeStatusColor[courseGrade.status?string]}"]
		[#if !courseGrade.passed]<font color='red'>${courseGrade.scoreText!}</font>[#else]${courseGrade.scoreText!}[/#if]
		[/@]
		[/#if]
		[@b.col width="5%" property="gp" title="绩点"]${((courseGrade.gp?default(0)*100)?int/100)?string('#0.00')?if_exists}[/@]
		[@b.col width="5%" property="passed" title="是否通过"]${(courseGrade.passed)?if_exists?string("是","<font color='red'>否</font>")}[/@]
		[@b.col width="7%" property="status" title="状态"]${gradeStatus[courseGrade.status?default(0)?string]!}[/@]
	[/@]
[/@]
[@b.foot/]