[#ftl]
[@b.head/]
[@b.toolbar title="修改教师职称"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!update?id=${teacherTitle.id}" theme="list"]
    [@b.textfield name="teacherTitle.code" label="代码" value="${teacherTitle.code!}" required="true" maxlength="20"/]
    [@b.textfield name="teacherTitle.name" label="名称" value="${teacherTitle.name!}" required="true" maxlength="20"/]
    [@b.textfield name="teacherTitle.enName" label="英文名" value="${teacherTitle.enName!}" maxlength="100"/]
    [@b.startend label="生效失效时间" 
      name="teacherTitle.beginOn,teacherTitle.endOn" required="false,false" 
      start=teacherTitle.beginOn end=teacherTitle.endOn format="date"/]
    [@b.textfield name="teacherTitle.remark" label="备注" value="${teacherTitle.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]